# Generated by Django 4.1.4 on 2023-01-09 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=65)),
                ('descriçao', models.CharField(max_length=165)),
                ('detalhes_produto', models.TextField()),
                ('marca', models.CharField(max_length=65)),
                ('preço', models.FloatField()),
                ('tamanho', models.CharField(max_length=50)),
                ('estoque', models.IntegerField()),
                ('unidade_tamanho', models.CharField(max_length=65)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('update_em', models.DateTimeField(auto_now=True)),
                ('publicado', models.BooleanField(default=False)),
                ('imagem', models.ImageField(upload_to='app/imagens/%Y/%m/%d')),
                ('categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.categoria')),
                ('sub_categoria', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.subcategoria')),
            ],
        ),
    ]
